apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-rabbit-site
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: some-rabbit
          image: rabbitmq:3
          ports:
            - containerPort: 5672
        - name: node-web-app
          image: emiru84/node-web-app:latest
          ports:
            - containerPort: 3000